" USER CONFIG

syntax enable
colorscheme industry

set number autoindent ruler

set tabstop=4 shiftwidth=4 softtabstop=4 expandtab

set hlsearch

set foldmethod=indent

"setlocal spell spelllang=en_us
