#!/usr/bin/env bash
# USER BASHRC (~/.bashrc)

[[ "${1:-}" == '-v' ]] \
    && echo "USER BASHRC SOURCED (~/.bashrc)..."

# shellcheck source=/Users/kend/Developer/bashenv
[[ -z "${bashenv:-}" && -d "${HOME}/Developer/bashenv" ]] \
    && export bashenv="${HOME}/Developer/bashenv"


## COLORIZE ROOT PROMPT
##
{
    if ((EUID==0)); then
        PS1='\h:\W \[\e[31;1m\]\u\$\[\e[0;0m\] '
        [[ ! -d ~/.history ]] && mkdir ~/.history

        export LESSHISTFILE=~/.history/less_history_sudo

        if [[ ! -f "${LESSHISTFILE}" ]]; then
            touch "${LESSHISTFILE}"
        fi
    fi
}


## ALIASES & FUNCTIONS
#
{
    ## SOURCE ALIASES
    #
    {
        # shellcheck source=/Users/kend/Developer/bashenv/components/bash_aliases
        if [[ -r "${bashenv}/components/bash_aliases" ]]; then
            . "${bashenv}/components/bash_aliases"
        fi
    }

    ## SOURCE FUNCTIONS
    #
    {
        export funcs="${bashenv:?}/components/funcs"
        if [[ ! -d "${funcs}" ]]; then
            unset funcs
        else
            __list_funcDir_contents ()
            {
                find "${funcs}" -type f -mindepth 1 -maxdepth 1 \! \( -name ".*" -or -name "*.swp" \)
                return
            }
            
            declare -xA funcnames
            funcnames=()

            while read -r funcpath; do
                #bn="$(basename "${funcpath}" | sed 's:\.[^.]*$::')"
                if [[ -r "${funcpath}" ]]; then
                    #shellcheck disable=1090
                    source "${funcpath}" \
                        && funcnames["$(basename "${funcpath}")"]="${funcpath}"
                fi
            done < <(__list_funcDir_contents)
        fi
    }

}


