#!/usr/bin/env bash
# USER BASH PROFILE (~/.bash_profile)

[[ "${1:-}" == '-v' ]] \
    && echo "USER BASH PROFILE SOURCED (~/.bash_profile)"

## LOCATION OF BASHENV REPOSITORY ROOT DIRECTORY
##  -> ~/Developer/bashenv

[[ -z "${bashenv:-}" ]] \
    && [[ -d "${HOME}/Developer/bashenv" ]] \
    && declare -xr bashenv="${HOME}/Developer/bashenv"

[[ -r ~/.profile ]] && . ~/.profile

[[ -r ~/.bashrc ]] && . ~/.bashrc


