#!/usr/bin/env sh
# USER SH CONFIG

printf "USER PROFILE SOURCED (%s)...\n" "~/.profile"

export MYNAME='Ken Dait'
export EMAIL='snaginanek@gmail.com'
export EDITOR='vim'
export SUDOEDITOR='vim'
export FCEDIT='vim'

shopt -s cdable_vars extglob

