#!/usr/bin/env bash
# USER BASH ALIASES

## LS ALIASES
#
{
    if [[ "$(uname -s)" == 'Darwin' ]]; then
        alias ls='/bin/ls -G'
    else
        alias ls='/bin/ls --color=auto'
    fi

    alias la='ls -A'
    alias ll='ls -l'
    alias lla='ls -lA'
    alias l1='ls -1'
    alias lm='ls -m'
    
    alias l.='ls -d .[^$.]* 2> /dev/null || echo "<no dot files>"'
    alias ll.='ls -dl .[^$.]* 2> /dev/null || echo "<no dot files>"'
    alias l1.='ls -d1 .[^$.]* 2> /dev/null || echo "<no dot files>"'
    alias lm.='ls -dm .[^$.]* 2> /dev/null || echo "<no dot files>"'

}

## COLORIZE
#
{
    alias grep='/usr/bin/grep --color=auto'
    alias egrep='/usr/bin/egrep --color=auto'
    alias fgrep='/usr/bin/fgrep --color=auto'

    # default: LSCOLORS='exfxcxdxbxegedabagacad'
    export LSCOLORS='gxfxcxdxbxegedabagacad'

    if command -v tree &> /dev/null; then
        alias tree='tree -C'
        alias t1='tree -L 1'
        alias t2='tree -L 2'
        alias t3='tree -L 3'
    fi
}

alias sbash='[ -r ~/.bash_profile ] && . ~/.bash_profile'

alias x='logout'
alias h='history'
alias j='jobs'
alias c='clear'


if [[ "$(uname -s)" == 'Darwin' ]]; then
    alias scpt='osascript'
    alias spro='system_profiler'
    
    if command -v brew &> /dev/null; then
        alias cask='brew cask'
        alias services='brew services'
    fi
fi
